title : Marauder's Mart
description : Mini-blockchain and A* algorithm for a pseudo-anonymous reselling platform
theme: minima                
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
github: [metadata]
permalink: pretty

navbar:
  - text: Overview
    url: "/overview"
  - text: Getting Started
    url: "/getting-started"
  - text: Project Structure
    url: "/project-structure"
  - text: API Endpoints
    url: "/api-endpoints"
  - text: Dependencies
    url: "/dependencies"
  - text: Features
    url: "/features"
  - text: Contributions
    url: "/contributions"
  - text: Licensing / Acknowledgement
    url: "/licensing"
